name: Code coverage workflow
on: [create]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    steps:
    - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git-lfs
          pip install -e .
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest -s --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
